# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [4]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
# from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [8]:
# Loading the output csv file generated in weatherpy to a dataframe
vacation_df=pd.read_csv("../WeatherPy/Output/city_weather.csv")
vacation_df

,Unnamed: 0,City,Country,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Date
0,0,Coyhaique,CL,-45.5752,-72.0662,38.34,99,100,3.67,1626230190
1,1,Punta Arenas,CL,-53.1500,-70.9167,26.71,93,75,3.44,1626229916
2,2,Busselton,AU,-33.6500,115.3333,57.04,67,49,18.25,1626230190
3,3,Ngerengere,TZ,-6.7500,38.1167,67.75,95,51,1.66,1626230191
4,4,Baft,IR,29.2340,56.6057,77.63,33,11,2.66,1626230191
...,...,...,...,...,...,...,...,...,...,...
563,563,Zhigansk,RU,66.7697,123.3711,68.59,65,32,16.73,1626230336
564,564,Woodward,US,36.4337,-99.3904,83.43,54,1,11.50,1626230336
565,565,Honiara,SB,-9.4333,159.9500,87.33,66,92,11.27,1626230052
566,566,Bayir,TR,37.2687,28.2167,64.92,44,0,4.23,1626230337
567,567,Mandeville,JM,18.0417,-77.5071,77.05,84,20,2.68,1626230061

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [ ]:
# Configuring gmaps with api key
gmaps.configure(api_key='api_keys/g_key')

In [ ]:
# 
locations = earthquake_df[['latitude', 'longitude']]
weights = earthquake_df['Humidity']

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure